import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Provider } from "@/components/ui/provider";
import { ColorModeButton } from "@/components/ui/color-mode"
import "./globals.css";

export const metadata: Metadata = {
  title: "План",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <ColorModeButton />
          {children}
        </Provider>
      </body>
    </html>
  );
}
