import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider";
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "@/components/Sidebar/General/default";
import "./globals.css";
import { ColorModeButton } from "@/components/ui/color-mode";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "План",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider>
          <main>
            <Sidebar />
            <ColorModeButton position="fixed" right="1rem" top="1rem"/>

            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
